FROM python:latest
WORKDIR /root
RUN apt-get update > /dev/null
RUN pip3 install mysql-connector-python > /dev/null

COPY initialize.py /root/initialize.py
RUN chmod +rwx /root/initialize.py

COPY tableUpdate.py /root/tableUpdate.py
RUN chmod +rwx /root/tableUpdate.py

COPY storeMoM.sh /root/storeMoM.sh
RUN chmod +rwx /root/storeMoM.sh